Issue 469 - Add Tests For REST API
Cezerin2/Server pull request #25
Opened 2019-01-06 11:34 UTC by maurosergiosilva

Migrated from cezerin/cezerin#557

Issue #469

Okay, so I know this is a big one, and probably something that should have been split up into smaller PR's, but, alas, here it is.

This is essentially setting up the testing environment using Mocha/Chai and adding some testing functionality for some of the main API routes, allowing for both Admin users and non-Admin users.

I did have to change the security/tokens.js response to essentially return the Authentication token in the JSON response, to allow for it to be available in the testing environment. With the e-mail only sign up, I'm not sure how to retrieve the login token without this change, but you may know of a better way to do this.

This is also assuming that developerMode is set to false, because otherwise anybody can access any API routes, which I feel like is not expected behavior in a production environment, so I went by that instead.

Hopefully there's something useful here to work with, even with a few tweaks!

2019-01-07 20:23 UTC, LuBuss commented
Can we please update the package.json to the latest version and run npm install and package-lock.json is out of date.

2019-01-31 04:30 UTC, ngoyal16 requested changes

2019-01-31 04:30 UTC, ngoyal16 commented on config/server/server.development.js
> -	developerMode: true
in development mode why the developerMode is false

2019-01-31 04:30 UTC, ngoyal16 commented on package.json
> +    "build": "NODE_ENV=test npm run compile && npm run theme:build && npm run webpack:admin",
why you have added NODE_ENV=test in production build command...

2019-01-31 04:30 UTC, ngoyal16 commented on src/api/server/services/security/tokens.js
> +				token: 'Bearer ' + extractedToken
if you return token in API response.. then it will be a very huge security issue.

because if I inspect in the network log... I can find it.. so, I just need to know what is the admin login email... I do not need to have access to their email account

2020-06-19 02:29 UTC, Himadu2000 commented
Removing due to inactivity, conflicts, unknown branch.

2020-06-19 02:29 UTC, closed without merging