Update package.json
Cezerin2/Server pull request #256
Opened 2020-05-30 06:51 UTC by Himadu2000

2020-05-31 18:00 UTC, vamcart approved these changes

2020-06-18 14:01 UTC, capfsb requested changes

2020-06-18 14:01 UTC, capfsb commented on package.json
> +    "setup": "tsc && node -r esm build/setup.js",
Is it works? Maybe you need this `tsc || true && node -r esm build/setup.js`
If you make `tsc || true` node anyway runs even tsc has errors

2020-06-19 02:05 UTC, Himadu2000 commented on package.json
> +    "setup": "tsc && node -r esm build/setup.js",
Yup this draft till those errors are fixed, once done then merge...

2020-08-26 00:34 UTC, closed without merging