Add Assets Base URL
Cezerin2/Server pull request #41
Opened 2019-01-31 12:44 UTC by LuBuss

2019-02-01 01:45 UTC, ngoyal16 requested changes

2019-02-01 01:45 UTC, ngoyal16 commented on config/server.js
>  	// used by API
Port and url is contradict

Running port is 3000
But store url is localhost:3003

2019-02-01 01:45 UTC, ngoyal16 commented on src/api/server/services/products/images.js
> +								settings.assetsBaseURL,
Add domain as alternative to it.

2019-02-01 01:45 UTC, ngoyal16 commented on src/api/server/services/products/products.js
>  			if (item.category_id) {
If domain is not used in functions. Don't pass it..

2019-02-01 10:19 UTC, LuBuss commented on src/api/server/services/products/products.js
>  			if (item.category_id) {
Domain is used in the function to the product url

2019-02-01 10:20 UTC, LuBuss commented on config/server.js
>  	// used by API
Updated store url back to 3000. was a late night commit

2019-02-06 07:39 UTC, ngoyal16 approved these changes

2019-02-06 08:06 UTC, merged