Docker
Cezerin2/Server pull request #57
Opened 2019-02-16 12:11 UTC by LuBuss

implement dockerfile

2019-02-17 06:36 UTC, ngoyal16 requested changes

2019-02-17 06:36 UTC, ngoyal16 commented on Dockerfile
> +
can add cezerin2 directly in single command 

after creating directly make workdir before running commands this way DOCKER FILE can be reduced.

2019-02-17 06:36 UTC, ngoyal16 commented on Dockerfile
> +
expose the listen port also add image optimizer to Nginx.

2019-02-18 10:02 UTC, LuBuss commented on Dockerfile
> +
don't feel nginx should be running here. I feel this should be happening on store and admin

2019-02-18 10:23 UTC, ngoyal16 commented on Dockerfile
> +
we need nginx here for image resizing part.

2019-02-21 15:05 UTC, closed without merging