Secure hash-based password authentication
Cezerin2/Server pull request #82
Opened 2019-03-15 19:42 UTC by JorgeFeijoom

Register, password recovery, login and profile edition hash-based

2019-03-15 20:49 UTC, lortschi commented
looks all fine to me

2019-03-16 04:40 UTC, ngoyal16 requested changes

2019-03-16 04:40 UTC, ngoyal16 commented on config/server.production.js
> +	smtpServer: {},
smtpServer setting should be back

2019-03-16 04:40 UTC, ngoyal16 commented on src/ajaxRouter.js
> +			api.customers.update(userId, customerDraft).then(({ status, json }) => {
use async/await for better managment

2019-03-16 04:40 UTC, ngoyal16 commented on src/ajaxRouter.js
> +		api.customers.list(filter).then(({ status, json }) => {
put asyn/await before promise function else it will not wait for results

2019-03-16 04:40 UTC, ngoyal16 commented on src/ajaxRouter.js
> +					api.customers.retrieve(result._id).then(({ status, json }) => {
async function when doing any call which is should be require in same thread

2019-03-16 04:40 UTC, ngoyal16 commented on src/index.js
> +	var allowedOrigins = [
do not hardcore cors header.. it should come to from config file.

2019-03-16 05:31 UTC, LuBuss commented on src/ajaxRouter.js
> +const saltRounds = 10;
Salt should be config option

2019-03-16 05:47 UTC, LuBuss reviewed
Agree with all @ngoyal16 comments

2019-03-16 13:51 UTC, JorgeFeijoom commented
- fixed hardcore CORS header
- smtp parameters on server.production.js
- set salt rounds on server conf
- fixed async/await on api calls and better management

2019-03-16 15:43 UTC, vamcart approved these changes

2019-03-16 16:32 UTC, ngoyal16 approved these changes
seems good to go

2019-03-16 17:05 UTC, ngoyal16 approved these changes

2019-03-16 17:06 UTC, merged