wait errors wrapped
Cezerin2/Server pull request #96
Opened 2019-03-25 16:08 UTC by dewelloper

Please recover wait errors in ajaxRouter

2019-03-26 09:26 UTC, LuBuss commented
I don't think catching all the errors and continue is all ways appropriate.

2019-03-26 11:46 UTC, dewelloper commented
finding error taking much time, catching and thrown errors usefull. Also, we have to wrap this codes becouse in feature this error will crush the application npm explaning about that. Please research about "UnhandledPromiseRejectionWarning" now application thrown that error while coming from register email when you click register button on email

2019-03-26 14:25 UTC, ngoyal16 requested changes

2019-03-26 14:25 UTC, ngoyal16 commented on src/ajaxRouter.js
> +					.update(userId, customerDraft)
if you are using await then why using .then and .catch block.

2019-03-26 16:33 UTC, vamcart commented
I have this error while register account with that new file from dewelloper:

(node:5523) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'catch' of undefined
    at registerCustomer (/home/work/My/1/test-clean/cezerin2/src/ajaxRouter.js:497:5)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:5523) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5523) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

2019-03-26 17:25 UTC, dewelloper commented on src/ajaxRouter.js
> +					.update(userId, customerDraft)
Nitin i will pr again youre right hince this code not all belong to me and i dont  care about every usage

2019-03-26 17:34 UTC, vamcart commented on src/ajaxRouter.js
> +					.update(userId, customerDraft)
Just add new commit with changes.
Your commit will be available in this PR automatically.

2019-03-27 04:32 UTC, ngoyal16 requested changes

2019-03-27 04:32 UTC, ngoyal16 commented on src/ajaxRouter.js
> +			const variant = OrderItemsService.getVariantFromProduct(
add async await here so it will wait until data not comes from the database

2019-03-27 04:32 UTC, ngoyal16 commented on src/ajaxRouter.js
> +			await handlebars
if await it there they why we are using .then .catch.. simple use try-catch block. and when there is error log it to Winston

2019-03-27 04:32 UTC, ngoyal16 commented on src/ajaxRouter.js
> +			await handlebars
need to be fix at every place.

2019-03-28 11:54 UTC, dewelloper commented on src/ajaxRouter.js
> +					.update(userId, customerDraft)
https://hackernoon.com/6-reasons-why-javascripts-async-await-blows-promises-away-tutorial-c7ec10518dd9

2019-03-28 19:24 UTC, ngoyal16 requested changes

2019-03-28 19:24 UTC, ngoyal16 commented on src/ajaxRouter.js
> +					.update(userId, customerDraft)
@dewelloper i know it is not your code but i appreciate if you can fix these issues..

2019-03-28 19:33 UTC, dewelloper commented
Ok i will send but there is some differency on my version you should compare with yours

2019-03-28 19:44 UTC, dewelloper commented
import express from 'express';
import jwt from 'jsonwebtoken';
import { ObjectID } from 'mongodb';
import CezerinClient from 'pz-client';
import handlebars from 'handlebars';
import serverSettings from './lib/settings';
import serverConfigs from '../../../config/server';
import { db } from './lib/mongo';
import AuthHeader from './lib/auth-header';
import mailer from './lib/mailer';
import EmailTemplatesService from './services/settings/emailTemplates';
import SettingsService from './services/settings/settings';

const ajaxRouter = express.Router();

const TOKEN_PAYLOAD = { email: 'store', scopes: ['admin'] };
const STORE_ACCESS_TOKEN = jwt.sign(TOKEN_PAYLOAD, serverSettings.jwtSecretKey);

const api = new CezerinClient({
	apiBaseUrl: serverSettings.apiBaseUrl,
	apiToken: STORE_ACCESS_TOKEN
});

const DEFAULT_CACHE_CONTROL = 'public, max-age=60';
const PRODUCTS_CACHE_CONTROL = 'public, max-age=60';
const PRODUCT_DETAILS_CACHE_CONTROL = 'public, max-age=60';

const getCartCookieOptions = isHttps => ({
	maxAge: 24 * 60 * 60 * 1000, // 24 hours
	httpOnly: true,
	signed: true,
	secure: isHttps,
	sameSite: 'strict'
});

const getIP = req => {
	let ip = req.get('x-forwarded-for') || req.ip;

	if (ip && ip.includes(', ')) {
		ip = ip.split(', ')[0];
	}

	if (ip && ip.includes('::ffff:')) {
		ip = ip.replace('::ffff:', '');
	}

	return ip;
};

const getUserAgent = req => {
	return req.get('user-agent');
};

const getVariantFromProduct = (product, variantId) => {
	if (product.variants && product.variants.length > 0) {
		return product.variants.find(
			variant => variant.id.toString() === variantId.toString()
		);
	} else {
		return null;
	}
};

const fillCartItemWithProductData = (products, cartItem) => {
	const product = products.find(p => p.id === cartItem.product_id);
	if (product) {
		cartItem.image_url =
			product.images && product.images.length > 0
				? product.images[0].url
				: null;
		cartItem.path = product.path;
		cartItem.stock_backorder = product.stock_backorder;
		cartItem.stock_preorder = product.stock_preorder;
		if (cartItem.variant_id && cartItem.variant_id.length > 0) {
			const variant = getVariantFromProduct(product, cartItem.variant_id);
			cartItem.stock_quantity = variant ? variant.stock_quantity : 0;
		} else {
			cartItem.stock_quantity = product.stock_quantity;
		}
	}
	return cartItem;
};

const fillCartItems = cartResponse => {
	let cart = cartResponse.json;
	if (cart && cart.items && cart.items.length > 0) {
		const productIds = cart.items.map(item => item.product_id);
		return api.products
			.list({
				ids: productIds,
				fields:
					'images,enabled,stock_quantity,variants,path,stock_backorder,stock_preorder'
			})
			.then(({ status, json }) => {
				const newCartItem = cart.items.map(cartItem =>
					fillCartItemWithProductData(json.data, cartItem)
				);
				cartResponse.json.items = newCartItem;
				return cartResponse;
			});
	} else {
		return Promise.resolve(cartResponse);
	}
};

ajaxRouter.get('/products', (req, res, next) => {
	let filter = req.query;
	filter.enabled = true;
	api.products.list(filter).then(({ status, json }) => {
		res
			.status(status)
			.header('Cache-Control', PRODUCTS_CACHE_CONTROL)
			.send(json);
	});
});

ajaxRouter.get('/products/:id', (req, res, next) => {
	api.products.retrieve(req.params.id).then(({ status, json }) => {
		res
			.status(status)
			.header('Cache-Control', PRODUCT_DETAILS_CACHE_CONTROL)
			.send(json);
	});
});

ajaxRouter.get('/cart', (req, res, next) => {
	const order_id = req.signedCookies.order_id;
	if (order_id) {
		api.orders
			.retrieve(order_id)
			.then(cartResponse => fillCartItems(cartResponse))
			.then(({ status, json }) => {
				json.browser = undefined;
				res.status(status).send(json);
			});
	} else {
		res.end();
	}
});

ajaxRouter.post('/reset-password', async (req, res, next) => {
	const data = {
		status: false,
		id: null,
		verified: false
	}

	const userId = 'token' in req.body ? AuthHeader.decodeUserLoginAuth(req.body.token) : AuthHeader.decodeUserLoginAuth(req.body.id).userId.userId;

	const filter = {
		id: userId
	}

	const customerDraft = {
		password: req.body.password
	}

	// update customer password after checking customer id
	if ('id' in req.body) {
		await api.customers.update(userId, customerDraft).then(({ status, json }) => {
			data.status = true;
			data.id = userId;
			data.verified = true;
			res.status(status).send(data);
		});
		return false;
	}
	
	if ('name' in userId && userId.name.indexOf('JsonWebTokenErro') !== -1) {
		res.send(data);
		return false;
	}

	// if customer email exists send status back
	await api.customers.list(filter).then(({ status, json }) => {
		if (json.total_count > 0) {
			data.status = true;
			data.id = AuthHeader.encodeUserLoginAuth(userId);
			res.status(status).send(data);
		}
		res.status(status).send(data);
	});
});

ajaxRouter.post('/forgot-password', async (req, res, next) => {
	const filter = {
		email: req.body.email
	}
	const data = {
		status: true
	}

	// send forgot password email
	async function sendEmail(userId) {
		const countryCode = undefined;
		const [emailTemp] = await Promise.all([EmailTemplatesService.getEmailTemplate(`forgot_password_${serverConfigs.language}`)]);
		await handlebars.registerHelper('forgot_password_link', function(obj) {
			var url  = `${serverConfigs.storeBaseUrl}${countryCode !== undefined ? `/${countryCode}/` : '/'}reset-password?token=${AuthHeader.encodeUserLoginAuth(userId)}`;
			var text = emailTemp.link;
			if (text == undefined) {
				text = url;
			}
			return new handlebars.SafeString( `<a style="position: relative;text-transform: uppercase;border: 1px solid #ccc;color: #000;padding: 5px;text-decoration: none;" value="${text}" href="${url}"> ${text} </a>` );
		});
		const [bodyTemplate, settings] = await Promise.all([handlebars.compile(emailTemp.body), SettingsService.getSettings()]);
		await Promise.all([
			mailer.send({
				to: req.body.email,
				subject: `${emailTemp.subject} ${settings.store_name}`,
				html: bodyTemplate({
					shop_name: settings.store_name
				})
			}), res.send(data)
		]);
	}

	// check if customer exists
	await api.customers.list(filter).then(({ status, json }) => {
		if (json.total_count < 1) {
			data.status = false;
			res.status(status).send(data);
			return false;
		}
		sendEmail(json.data[0].id);
	});
});

ajaxRouter.post('/customer-account', async (req, res, next) => {
	const customerData = {
		token: '',
		authenticated: false,
		customer_settings: null,
		order_statuses: null
	};

	customerData.token = AuthHeader.decodeUserLoginAuth(req.body.token);
	const userId = JSON.stringify(customerData.token.userId).replace(/["']/g, "");
	const filter = {
		customer_id: userId
	}

	// retrieve customer data
	await api.customers.retrieve(userId).then(({ status, json }) => {
		customerData.customer_settings = json;
		customerData.customer_settings.password = '*******';
		customerData.token = AuthHeader.encodeUserLoginAuth(userId);
		customerData.authenticated = false;
	});

	// retrieve orders data
	await api.orders.list(filter).then(({ status, json }) => {
		customerData.order_statuses = json;
		let objJsonB64 = JSON.stringify(customerData);
		objJsonB64 = Buffer.from(objJsonB64).toString("base64");
		res.status(status).send(JSON.stringify(objJsonB64));
	});
});

ajaxRouter.post('/login', async (req, res, next) => {
	const customerData = {
		token: '',
		authenticated: false,
		loggedin_failed: false,
		customer_settings: null,
		order_statuses: null,
		cartLayer: req.body.cartLayer !== undefined ? req.body.cartLayer : false
	};
			
	// check if customer exists in database and grant or denie access
	await db.collection('customers').find({email: req.body.email, password: AuthHeader.decodeUserPassword(req.body.password).password}).limit(1).next(function getCustomerData(error, result) {
		if (error) {
			//alert
			throw error;
		}
		if (!result){
			api.customers.list().then(({ status, json }) => {
				customerData.loggedin_f [...]

2020-04-21 08:48 UTC, closed without merging